# /odoo-dev/docker-compose.yml

version: "2"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  web:
    image: odoo:latest
    depend_on: -db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    # command: odoo scaffold /mnt/extra-addons/custom_module
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
